[tool.poetry]
name = "reconstrain"
version = "0.1.0"
description = "Constrained reinforcement learning."
authors = ["Damian Owerko <damowerko@gmail.com>"]
license = "MIT"
readme = "README.md"

[[tool.poetry.source]]
name = "pytorch"
url = "https://eternalphane.github.io/pytorch-pypi/"

[tool.poetry.dependencies]
python = "^3.9,<3.11"
torch = "1.10.1+cu113"
pytorch-lightning = "^1.5.9"
numpy = "^1.22.1"
matplotlib = "^3.5.1"
PySide6 = "^6.2.2.1"
gym = "^0.21.0"
scipy = "^1.8.0"

[tool.poetry.group.dev.dependencies]
black = "^21.12-beta.0"
jupyter = "^1.0.0"
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"