[tool.poetry]
name = "motion_planning"
version = "0.1.0"
description = "Constrained reinforcement learning."
authors = ["Damian Owerko <damowerko@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
torch = {version = "=2.0.0"}
torch-geometric = {version = "^2.3.1"}
pytorch-lightning = "^2.0.5"
numpy = "^1.21.1"
matplotlib = "^3.5.1"
PySide6 = "^6.2.2.1"
gym = "^0.26.2"
stable-baselines3 = "^2.2.1"
scipy = "^1.8.0"
torch-sparse = "^0.6.18+pt20cu118"
torch-cluster = "^1.6.3+pt20cu118"
torch-scatter = "^2.1.2+pt20cu118"
networkx = "^2.7.1"
numba = ">=0.55.1"
torchcps = {git = "https://github.com/Damowerko/torchcps"}
imageio = "^2.34.0"

[tool.poetry.group.dev.dependencies]
black = "^21.12-beta.0"
jupyter = "^1.0.0"
pytest = "^7.0.0"
guildai = "^0.8.1"
snakeviz = "^2.1.1"
mypy = "^0.942"

[[tool.poetry.source]]
name = "PyPI"
priority = "supplemental"

[[tool.poetry.source]]
name = "pyg"
url = "https://data.pyg.org/whl/torch-2.0.0+cu118.html"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"